swagger: "2.0"
tags:
  - name: market
    description: accepts market as query param 
    version: "1.0"
host: localhost:5000
basePath: /api/v1
schemes:
  - http
parameters:
        - name: x-access-tokens
          in: header
          type: string
          required: False
          description: JWT token for authorization
        - name: market
          in: query
          description: Filter by market symbol e.g. (LTC-BTC)
          type: string
        
responses:
        200:
          description: OK
          schema:
              properties:
                high:
                  type: string
                low:
                  type: string
                percentChange:
                  type: string
                quoteVolume:
                  type: string
                symbol:
                  type: string
                updatedAt:
                  type: string
                volume:
                  type: string
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
security:
        - JWT: []
